version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/Caledfwlch1/temp
    steps:
      - run: go get github.com/Caledfwlch1/temp/...
      - checkout
  tbuilds:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Builds!
          command:  |
            #go get github.com/Caledfwlch1/temp
            go test github.com/Caledfwlch1/temp/runcurl -run TestBuilds
  tcurlst:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Curlst!
          timeout: 1000
          command:  |
            #go get github.com/Caledfwlch1/temp/runcurl
            go test github.com/Caledfwlch1/temp/runcurl -run TestCurlst
  tthreshold:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Threshold!
          command:  |
            #go get github.com/Caledfwlch1/temp/runcurl
            go test github.com/Caledfwlch1/temp/runcurl -run TestThreshold
  tfailed_nodes:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Failed_nodes!
          timeout: 1000
          command:  |
            #go get github.com/Caledfwlch1/temp/runcurl
            go test github.com/Caledfwlch1/temp/runcurl -run TestFailed_nodes
  tdbdelays:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Dbdelays!
          command:  |
            #go get github.com/Caledfwlch1/temp/runcurl
            go test github.com/Caledfwlch1/temp/runcurl -run TestDbdelays
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Environment
          command: |
            echo "export1"
            export
      - run:
          name: Run test
          command: |
            #go get github.com/Caledfwlch1/temp/temp
            go test -v github.com/Caledfwlch1/temp/temp
            echo "export2"
            export
workflows:
  version: 2
  start_build:
    jobs:
      - build
      - tbuilds:
          requires:
            - build
      - tcurlst:
          requires:
            - build
      - tthreshold:
          requires:
            - build
      - tfailed_nodes:
          requires:
            - build
      - tdbdelays:
          requires:
            - build
      - test:
          requires:
            - tbuilds
            - tcurlst
            - tthreshold
            - tfailed_nodes
            - tdbdelays
