version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/Caledfwlch1/temp
    steps:
      - checkout
  tbuilds:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Builds!
          environment:
            GOPATH: $GOPATH:/go/src/github.com/Caledfwlch1/temp/
          command:  |
            export | grep GO
            go get github.com/Caledfwlch1/temp
            ls -l /go/src/github.com/Caledfwlch1/temp/runcurl
            export | grep GO
            go test -v /go/src/github.com/Caledfwlch1/temp/runcurl/builds_test.go
  tcurlst:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Curlst!
          command:  |
            go get github.com/Caledfwlch1/temp/runcurl
            go test -v /go/src/github.com/Caledfwlch1/temp/runcurl/curlst_test.go
  tthreshold:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Threshold!
          command:  |
            go get github.com/Caledfwlch1/temp/runcurl
            go test -v /go/src/github.com/Caledfwlch1/temp/runcurl/threshold_test.go
  tfailed_nodes:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Failed_nodes!
          command:  |
            go get github.com/Caledfwlch1/temp/runcurl
            go test -v /go/src/github.com/Caledfwlch1/temp/runcurl/failed_nodes_test.go
  tdbdelays:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Dbdelays!
          command:  |
            go get github.com/Caledfwlch1/temp/runcurl
            go test -v /go/src/github.com/Caledfwlch1/temp/runcurl/dbdelays_test.go
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Environment
          command: |
            echo "export1"
            export
      - run:
          name: Run test
          command: |
            go get github.com/Caledfwlch1/temp/temp
            go test -v github.com/Caledfwlch1/temp/temp
            echo "export2"
            export
workflows:
  version: 2
  start_build:
    jobs:
      - build
      - tbuilds:
          requires:
            - build
      - tcurlst:
          requires:
            - build
      - tthreshold:
          requires:
            - build
      - tfailed_nodes:
          requires:
            - build
      - tdbdelays:
          requires:
            - build
      - test:
          requires:
            - tbuilds
            - tcurlst
            - tthreshold
            - tfailed_nodes
            - tdbdelays
