version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/Caledfwlch1/temp
    steps:
      - checkout
      - run:
          name: Get package
          command: go get github.com/Caledfwlch1/temp/runcurl
  bigsleep:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Big sleep!
          command: go run runcurl/runcurl.go -u="http://35.190.167.185/custom?branch=dev&commit=6c910dffc96d6a4d0c5a32fc6f53bc4f9d050570&roles=builds&wait=true"
  shortsleep:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Short sleep!
          command: sleep 60
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Environment
          command: |
            echo "export1"
            export
      - run:
          name: Run test
          #environment:
            #PAKETS: github.com/Caledfwlch1/temp
          command: |
            go get github.com/Caledfwlch1/temp/temp
            go test -v github.com/Caledfwlch1/temp/temp
            echo "export2"
            export
workflows:
  version: 2
  start_build:
    jobs:
      - build
      - shortsleep:
          requires:
            - build
      - test:
          requires:
            - shortsleep
            - bigsleep
      - bigsleep:
          requires:
            - build
