version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
        environment:
          GOROOT: /usr/local/go
    working_directory: /go/src/github.com/Caledfwlch1/temp
    steps:
      - checkout
  bigsleep:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Big sleep!
          command: sleep 5
  shortsleep:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Short sleep!
          command: sleep 5
  test:
    docker:
      - image: circleci/golang:1.8
    steps:
      - run:
          name: Environment
          #environment:
            #GOPATH: /go
            #:/home/circleci/project
            #GOROOT: /usr/local/go
          command: |
            echo "export1"
            export
      - run:
          name: Run test
          #environment:
            #PAKETS: github.com/Caledfwlch1/temp
          command: |
            go get github.com/Caledfwlch1/temp/temp
            go test -v github.com/Caledfwlch1/temp/temp
            echo "export2"
            export
workflows:
  version: 2
  start_build:
    jobs:
      - build
      - shortsleep:
          requires:
            - build
      - test:
          requires:
            - shortsleep
            - bigsleep
      - bigsleep:
          requires:
            - build
